namespace AspireFileDisplayExtension.Monaco;

using System.Collections.Generic;

public static class MonacoLanguageExtensions
{
    /// <summary>
    /// Returns the Monaco language ID string for a given enum value.
    /// </summary>
    public static string ToMonacoId(this MonacoLanguage language) =>
        MonacoLanguageIds.TryGetValue(language, out var id) ? id : "plaintext";

    /// <summary>
    /// Tries to resolve a MonacoLanguage from a file extension (with or without leading dot).
    /// </summary>
    public static bool TryGetFromExtension(string extension, out MonacoLanguage language)
    {
        var ext = extension.TrimStart('.').ToLowerInvariant();
        return ExtensionMap.TryGetValue(ext, out language);
    }

    private static readonly Dictionary<MonacoLanguage, string> MonacoLanguageIds = new()
    {
        [MonacoLanguage.Abap] = "abap",
        [MonacoLanguage.Apex] = "apex",
        [MonacoLanguage.Azcli] = "azcli",
        [MonacoLanguage.Bat] = "bat",
        [MonacoLanguage.Bicep] = "bicep",
        [MonacoLanguage.Cameligo] = "cameligo",
        [MonacoLanguage.Clojure] = "clojure",
        [MonacoLanguage.Coffee] = "coffeescript",
        [MonacoLanguage.Cpp] = "cpp",
        [MonacoLanguage.Csharp] = "csharp",
        [MonacoLanguage.Csp] = "csp",
        [MonacoLanguage.Css] = "css",
        [MonacoLanguage.Cypher] = "cypher",
        [MonacoLanguage.Dart] = "dart",
        [MonacoLanguage.Dockerfile] = "dockerfile",
        [MonacoLanguage.Ecl] = "ecl",
        [MonacoLanguage.Elixir] = "elixir",
        [MonacoLanguage.Flow9] = "flow9",
        [MonacoLanguage.Freemarker2] = "freemarker2",
        [MonacoLanguage.Fsharp] = "fsharp",
        [MonacoLanguage.Go] = "go",
        [MonacoLanguage.Graphql] = "graphql",
        [MonacoLanguage.Handlebars] = "handlebars",
        [MonacoLanguage.Hcl] = "hcl",
        [MonacoLanguage.Html] = "html",
        [MonacoLanguage.Ini] = "ini",
        [MonacoLanguage.Java] = "java",
        [MonacoLanguage.Javascript] = "javascript",
        [MonacoLanguage.Julia] = "julia",
        [MonacoLanguage.Kotlin] = "kotlin",
        [MonacoLanguage.Less] = "less",
        [MonacoLanguage.Lexon] = "lexon",
        [MonacoLanguage.Liquid] = "liquid",
        [MonacoLanguage.Lua] = "lua",
        [MonacoLanguage.M3] = "m3",
        [MonacoLanguage.Markdown] = "markdown",
        [MonacoLanguage.Mdx] = "mdx",
        [MonacoLanguage.Mips] = "mips",
        [MonacoLanguage.Msdax] = "msdax",
        [MonacoLanguage.Mysql] = "mysql",
        [MonacoLanguage.Objective_c] = "objective-c",
        [MonacoLanguage.Pascal] = "pascal",
        [MonacoLanguage.Pascaligo] = "pascaligo",
        [MonacoLanguage.Perl] = "perl",
        [MonacoLanguage.Pgsql] = "pgsql",
        [MonacoLanguage.Php] = "php",
        [MonacoLanguage.Pla] = "pla",
        [MonacoLanguage.Postiats] = "postiats",
        [MonacoLanguage.Powerquery] = "powerquery",
        [MonacoLanguage.Powershell] = "powershell",
        [MonacoLanguage.Proto] = "proto",
        [MonacoLanguage.Pug] = "pug",
        [MonacoLanguage.Python] = "python",
        [MonacoLanguage.Qsharp] = "qsharp",
        [MonacoLanguage.R] = "r",
        [MonacoLanguage.Razor] = "razor",
        [MonacoLanguage.Redis] = "redis",
        [MonacoLanguage.Redshift] = "redshift",
        [MonacoLanguage.Restructuredtext] = "restructuredtext",
        [MonacoLanguage.Ruby] = "ruby",
        [MonacoLanguage.Rust] = "rust",
        [MonacoLanguage.Sb] = "sb",
        [MonacoLanguage.Scala] = "scala",
        [MonacoLanguage.Scheme] = "scheme",
        [MonacoLanguage.Scss] = "scss",
        [MonacoLanguage.Shell] = "shell",
        [MonacoLanguage.Solidity] = "sol",
        [MonacoLanguage.Sophia] = "sophia",
        [MonacoLanguage.Sparql] = "sparql",
        [MonacoLanguage.Sql] = "sql",
        [MonacoLanguage.St] = "st",
        [MonacoLanguage.Swift] = "swift",
        [MonacoLanguage.Systemverilog] = "systemverilog",
        [MonacoLanguage.Tcl] = "tcl",
        [MonacoLanguage.Twig] = "twig",
        [MonacoLanguage.Typescript] = "typescript",
        [MonacoLanguage.Typespec] = "typespec",
        [MonacoLanguage.Vb] = "vb",
        [MonacoLanguage.Wgsl] = "wgsl",
        [MonacoLanguage.Xml] = "xml",
        [MonacoLanguage.Yaml] = "yaml",
        [MonacoLanguage.Json] = "json",
        [MonacoLanguage.PlainText] = "plaintext",
    };

    /// <summary>
    /// Maps file extensions (without dot, lowercase) to MonacoLanguage enum values.
    /// </summary>
    public static readonly Dictionary<string, MonacoLanguage> ExtensionMap = new()
    {
        ["abap"] = MonacoLanguage.Abap,
        ["cls"] = MonacoLanguage.Apex,
        ["azcli"] = MonacoLanguage.Azcli,
        ["bat"] = MonacoLanguage.Bat,
        ["cmd"] = MonacoLanguage.Bat,
        ["bicep"] = MonacoLanguage.Bicep,
        ["mligo"] = MonacoLanguage.Cameligo,
        ["clj"] = MonacoLanguage.Clojure,
        ["cljs"] = MonacoLanguage.Clojure,
        ["cljc"] = MonacoLanguage.Clojure,
        ["edn"] = MonacoLanguage.Clojure,
        ["coffee"] = MonacoLanguage.Coffee,
        ["c"] = MonacoLanguage.Cpp,
        ["h"] = MonacoLanguage.Cpp,
        ["cpp"] = MonacoLanguage.Cpp,
        ["cc"] = MonacoLanguage.Cpp,
        ["cxx"] = MonacoLanguage.Cpp,
        ["hpp"] = MonacoLanguage.Cpp,
        ["hh"] = MonacoLanguage.Cpp,
        ["cs"] = MonacoLanguage.Csharp,
        ["css"] = MonacoLanguage.Css,
        ["dart"] = MonacoLanguage.Dart,
        ["dockerfile"] = MonacoLanguage.Dockerfile,
        ["ecl"] = MonacoLanguage.Ecl,
        ["ex"] = MonacoLanguage.Elixir,
        ["exs"] = MonacoLanguage.Elixir,
        ["fs"] = MonacoLanguage.Fsharp,
        ["fsi"] = MonacoLanguage.Fsharp,
        ["fsx"] = MonacoLanguage.Fsharp,
        ["go"] = MonacoLanguage.Go,
        ["graphql"] = MonacoLanguage.Graphql,
        ["gql"] = MonacoLanguage.Graphql,
        ["hbs"] = MonacoLanguage.Handlebars,
        ["handlebars"] = MonacoLanguage.Handlebars,
        ["tf"] = MonacoLanguage.Hcl,
        ["tfvars"] = MonacoLanguage.Hcl,
        ["hcl"] = MonacoLanguage.Hcl,
        ["html"] = MonacoLanguage.Html,
        ["htm"] = MonacoLanguage.Html,
        ["ini"] = MonacoLanguage.Ini,
        ["cfg"] = MonacoLanguage.Ini,
        ["properties"] = MonacoLanguage.Ini,
        ["java"] = MonacoLanguage.Java,
        ["js"] = MonacoLanguage.Javascript,
        ["cjs"] = MonacoLanguage.Javascript,
        ["mjs"] = MonacoLanguage.Javascript,
        ["jl"] = MonacoLanguage.Julia,
        ["kt"] = MonacoLanguage.Kotlin,
        ["kts"] = MonacoLanguage.Kotlin,
        ["less"] = MonacoLanguage.Less,
        ["liq"] = MonacoLanguage.Liquid,
        ["liquid"] = MonacoLanguage.Liquid,
        ["lua"] = MonacoLanguage.Lua,
        ["md"] = MonacoLanguage.Markdown,
        ["mdx"] = MonacoLanguage.Mdx,
        ["s"] = MonacoLanguage.Mips,
        ["m"] = MonacoLanguage.Objective_c,
        ["pas"] = MonacoLanguage.Pascal,
        ["p"] = MonacoLanguage.Pascal,
        ["pl"] = MonacoLanguage.Perl,
        ["pm"] = MonacoLanguage.Perl,
        ["php"] = MonacoLanguage.Php,
        ["php3"] = MonacoLanguage.Php,
        ["php4"] = MonacoLanguage.Php,
        ["php5"] = MonacoLanguage.Php,
        ["phtml"] = MonacoLanguage.Php,
        ["pq"] = MonacoLanguage.Powerquery,
        ["ps1"] = MonacoLanguage.Powershell,
        ["psm1"] = MonacoLanguage.Powershell,
        ["psd1"] = MonacoLanguage.Powershell,
        ["proto"] = MonacoLanguage.Proto,
        ["pug"] = MonacoLanguage.Pug,
        ["jade"] = MonacoLanguage.Pug,
        ["py"] = MonacoLanguage.Python,
        ["pyw"] = MonacoLanguage.Python,
        ["qs"] = MonacoLanguage.Qsharp,
        ["r"] = MonacoLanguage.R,
        ["cshtml"] = MonacoLanguage.Razor,
        ["rst"] = MonacoLanguage.Restructuredtext,
        ["rb"] = MonacoLanguage.Ruby,
        ["rs"] = MonacoLanguage.Rust,
        ["scala"] = MonacoLanguage.Scala,
        ["sc"] = MonacoLanguage.Scala,
        ["scm"] = MonacoLanguage.Scheme,
        ["scss"] = MonacoLanguage.Scss,
        ["sh"] = MonacoLanguage.Shell,
        ["bash"] = MonacoLanguage.Shell,
        ["zsh"] = MonacoLanguage.Shell,
        ["sol"] = MonacoLanguage.Solidity,
        ["sparql"] = MonacoLanguage.Sparql,
        ["rq"] = MonacoLanguage.Sparql,
        ["sql"] = MonacoLanguage.Sql,
        ["swift"] = MonacoLanguage.Swift,
        ["sv"] = MonacoLanguage.Systemverilog,
        ["svh"] = MonacoLanguage.Systemverilog,
        ["tcl"] = MonacoLanguage.Tcl,
        ["twig"] = MonacoLanguage.Twig,
        ["ts"] = MonacoLanguage.Typescript,
        ["tsx"] = MonacoLanguage.Typescript,
        ["tsp"] = MonacoLanguage.Typespec,
        ["vb"] = MonacoLanguage.Vb,
        ["wgsl"] = MonacoLanguage.Wgsl,
        ["xml"] = MonacoLanguage.Xml,
        ["xsd"] = MonacoLanguage.Xml,
        ["xsl"] = MonacoLanguage.Xml,
        ["xslt"] = MonacoLanguage.Xml,
        ["svg"] = MonacoLanguage.Xml,
        ["yaml"] = MonacoLanguage.Yaml,
        ["yml"] = MonacoLanguage.Yaml,
        ["json"] = MonacoLanguage.Json,
        ["jsonc"] = MonacoLanguage.Json,
        ["txt"] = MonacoLanguage.PlainText,
    };
}


