IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Employee')
BEGIN

CREATE TABLE Employee (
	ID INT PRIMARY KEY, 
	Name NVARCHAR(100),
	IDepartment INT,
	CreatedAt DATETIME DEFAULT GETDATE()
);
END

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Department')
BEGIN

CREATE TABLE Department (
	ID INT PRIMARY KEY,
	Name NVARCHAR(100),
	CreatedAt DATETIME DEFAULT GETDATE()
);
END




